name: MMap

web: "[http://sharedhat.com](http://sharedhat.com)"

description: "Map using Google Maps Api Version 3. A comprehensible map can be displayed by using the custom marker."

authors: "[Noritaka Horio](http://sharedhat.com)"

license: "[MIT License](http://holyshared.github.com/MMap/license.txt)"

copyright: "&copy; [Noritaka Horio](http://sharedhat.com)"

sources:
  - "Source/Core/MMap.Core.js"
  - "Source/Core/MMap.Container.js"
  - "Source/Core/MMap.OverlayView.js"
  - "Source/Utils/MMap.Utils.js"
  - "Source/Marker/MMap.Marker.js"
  - "Source/Marker/MMap.Marker.Image.js"
  - "Source/Marker/MMap.Marker.Images.js"
  - "Source/Marker/MMap.MarkerManager.js"
  - "Source/Marker/MMap.MarkerLoader.js"
  - "Source/Window/MMap.Window.js"

author: holyshared

category: Interface

tags: [thumnail, google map, map, marker]

current: 0.2

#docs: http://url.to.docs

demo: http://holyshared.github.com/MMap